name: Python Script Workflow

on: [push]

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Python script
        env:
          API_KEY: ${{ secrets.REDDIT_API_KEY }}
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        run: python your_script.py
